spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  cache:
    type: simple
springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true